language: r
r:
 - oldrel
 - release
 - devel
 - 3.2
os:
  - linux
  - windows
  - osx
matrix:
  allow_failures:
    - os: osx
before_script:
 - Rscript -e 'devtools::install_github("jimhester/covr")'
after_success:
 - Rscript -e 'covr::codecov()'
