language: r
sudo: false
r:
 - oldrel
 - release
 - devel
 - 3.2
os:
  - linux
  - osx
matrix:
  allow_failures:
    - os: osx
      r: devel
    - os: osx
      r: 3.2
before_script:
 - Rscript -e 'devtools::install_github("jimhester/covr")'
after_success:
 - Rscript -e 'covr::codecov()'
