language: r
sudo: false
r:
 - oldrel
 - release
 - devel
 - 3.2
os:
  - linux
  - osx
before_script:
 - Rscript -e 'devtools::install_github("jimhester/covr")'
after_success:
 - Rscript -e 'covr::codecov()'
 