# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.githubusercontent.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
install:
  ps: Bootstrap

# Adapt as necessary starting from here

build_script:
  - travis-tool.sh install_deps
  - travis-tool.sh github_package jimhester/covr

test_script:
  - travis-tool.sh run_tests

on_failure:
  - travis-tool.sh dump_logs

on_success:
  - Rscript -e "covr::codecov()"

environment:
  NOT_CRAN: true
  
  matrix:
  - R_VERSION: release

  - R_VERSION: oldrel

  - R_VERSION: devel
    PKGTYPE: source

matrix:
  allow_failures:
    - R_VERSION: devel
