# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

cache:
  - C:\RLibrary

# Adapt as necessary starting from here
environment:
  global:
    WARNINGS_ARE_ERRORS: 1
    _R_CHECK_FORCE_SUGGESTS_: 0
    R_ARCH: x64
    USE_RTOOLS: true

  matrix:
  - R_VERSION: release

  - R_VERSION: oldrel

  - R_VERSION: devel
    PKGTYPE: source

build_script:
  - travis-tool.sh install_deps
  - travis-tool.sh github_package jimhester/covr

test_script:
  - travis-tool.sh run_tests

on_success:
  - Rscript -e "covr::codecov()"
